version: '3.1'
services:
  bot:
    build:
      dockerfile: ./docker/go/Dockerfile
      context: ./
    working_dir: /go/src
    command: go run main.go
    volumes:
      - ./src:/go/src

  ticker:
    build:
      dockerfile: ./docker/go/Dockerfile
      context: ./
    working_dir: /go/src
    command: go run ticker.go
    volumes:
      - ./src:/go/src

  mysql:
    image: mysql:5.7
    command: mysqld --sql-mode="NO_ENGINE_SUBSTITUTION"

